/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.kiran.gradle;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        System.out.println(new App().getGreeting());
        
        Product product = new Product("Allen Solly","Black Shirt",2000.0);
        System.out.println(product);
    }
}
